version: "3.8"

services:
  webhook:
    build:
      context: .
      dockerfile: docker/Dockerfile.webhook
    env_file:
      - .env
    environment:
      # Evita estourar max_connections no Postgres
      PRISMA_CONNECTION_LIMIT: "5"
    ports:
      - "4010:4010"
    restart: unless-stopped

  nfe_webhook:
    build:
      context: .
      dockerfile: docker/Dockerfile.nfe-webhook
    env_file:
      - .env
    environment:
      PRISMA_CONNECTION_LIMIT: "1"
    ports:
      - "4012:4012"
    restart: unless-stopped

  realtime:
    build:
      context: .
      dockerfile: docker/Dockerfile.realtime
    env_file:
      - .env
    environment:
      PRISMA_CONNECTION_LIMIT: "1"
    ports:
      - "3011:3011"
    restart: unless-stopped

  workers:
    build:
      context: .
      dockerfile: docker/Dockerfile.workers
    env_file:
      - .env
    environment:
      PRISMA_CONNECTION_LIMIT: "5"
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data


volumes:
  redis_data:

